{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vrata.fullname" . }}-controller
  labels:
    {{- include "vrata.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $cfg := .Values.controller.config | deepCopy }}
    {{- if not (dig "controlPlaneUrl" "" $cfg) }}
    {{- $url := printf "http://%s:%d" (include "vrata.cpName" .) (int .Values.controlPlane.service.port) }}
    {{- $_ := set $cfg "controlPlaneUrl" $url }}
    {{- end }}
    {{- toYaml $cfg | nindent 4 }}
{{- end }}
