{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vrata.fullname" . }}-controller
  labels:
    {{- include "vrata.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vrata.fullname" . }}-controller
  labels:
    {{- include "vrata.labels" . | nindent 4 }}
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "gateways"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["referencegrants"]
    verbs: ["get", "list", "watch"]
  {{- if .Values.controller.config.watch.superHttpRoutes }}
  - apiGroups: ["vrata.io"]
    resources: ["superhttproutes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["vrata.io"]
    resources: ["superhttproutes/status"]
    verbs: ["get", "patch", "update"]
  {{- end }}
  {{- if .Values.controller.config.leaderElection.enabled }}
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vrata.fullname" . }}-controller
  labels:
    {{- include "vrata.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vrata.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "vrata.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
