// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Rutoso project",
            "url": "https://github.com/achetronic/rutoso"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/groups": {
            "get": {
                "description": "Returns the full list of route groups known to this control plane.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List all route groups",
                "responses": {
                    "200": {
                        "description": "List of route groups (may be empty)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.RouteGroup"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new route group. The name must be unique across all groups.\nThe ID is auto-generated and returned in the response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Create a route group",
                "parameters": [
                    {
                        "description": "Route group to create",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RouteGroup"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Route group created",
                        "schema": {
                            "$ref": "#/definitions/model.RouteGroup"
                        }
                    },
                    "400": {
                        "description": "Invalid payload or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "A group with the same name already exists",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/{groupId}": {
            "get": {
                "description": "Returns a single route group by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get a route group",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Route group found",
                        "schema": {
                            "$ref": "#/definitions/model.RouteGroup"
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "put": {
                "description": "Replaces a route group's metadata (prefix, hostnames, headers, description).\nThe group's routes are not affected by this operation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Update a route group",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated route group",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RouteGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Route group updated",
                        "schema": {
                            "$ref": "#/definitions/model.RouteGroup"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a route group and all of its routes. This action is irreversible.\nThe xDS snapshot is updated immediately; Envoy will stop routing those rules.",
                "tags": [
                    "groups"
                ],
                "summary": "Delete a route group",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Group deleted"
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/{groupId}/routes": {
            "get": {
                "description": "Returns all routes that belong to the specified route group.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "List routes in a group",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of routes (may be empty)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Route"
                            }
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new route to the specified group.\nAt least one backend is required. If multiple backends are provided,\ntheir weights must sum to exactly 100 (weighted routing / canary).\nTwo routes with the same path rule (path/pathPrefix/pathRegex) in the\nsame group are considered duplicates and will be rejected with 409.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Create a route",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Route to create",
                        "name": "route",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Route"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Route created",
                        "schema": {
                            "$ref": "#/definitions/model.Route"
                        }
                    },
                    "400": {
                        "description": "Invalid payload, missing backend, or invalid weights",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "A route with the same match rule already exists",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/{groupId}/routes/{routeId}": {
            "get": {
                "description": "Returns a single route by its ID within the specified group.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Get a route",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
                        "description": "Route UUID",
                        "name": "routeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Route found",
                        "schema": {
                            "$ref": "#/definitions/model.Route"
                        }
                    },
                    "404": {
                        "description": "Group or route not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "put": {
                "description": "Replaces an existing route entirely.\nIf multiple backends are provided, their weights must sum to 100.\nChanging the match rule to one already used by another route in the same\ngroup will be rejected with 409.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Update a route",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
                        "description": "Route UUID",
                        "name": "routeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated route",
                        "name": "route",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Route"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Route updated",
                        "schema": {
                            "$ref": "#/definitions/model.Route"
                        }
                    },
                    "400": {
                        "description": "Invalid payload or invalid weights",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Group or route not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Match rule conflicts with another route",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a route from its group. The xDS snapshot is updated immediately.",
                "tags": [
                    "routes"
                ],
                "summary": "Delete a route",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
                        "description": "Route UUID",
                        "name": "routeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Route deleted"
                    },
                    "404": {
                        "description": "Group or route not found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Backend": {
            "type": "object",
            "properties": {
                "host": {
                    "description": "Host is the upstream hostname or IP address.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a unique identifier for this backend within the route.\nIt maps to an Envoy cluster name.",
                    "type": "string"
                },
                "port": {
                    "description": "Port is the upstream TCP port.",
                    "type": "integer"
                },
                "tls": {
                    "description": "TLS indicates whether the connection to the upstream should use TLS.",
                    "type": "boolean"
                },
                "weight": {
                    "description": "Weight controls what percentage of traffic is sent to this backend\nwhen multiple backends are defined. Values across all backends in a\nroute must sum to 100.",
                    "type": "integer"
                }
            }
        },
        "model.HeaderMatcher": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the header name (case-insensitive).",
                    "type": "string"
                },
                "regex": {
                    "description": "Regex indicates that Value should be treated as a regular expression.",
                    "type": "boolean"
                },
                "value": {
                    "description": "Value is the exact value the header must have.\nIf empty, only the presence of the header is checked.",
                    "type": "string"
                }
            }
        },
        "model.MatchRule": {
            "type": "object",
            "properties": {
                "headers": {
                    "description": "Headers are additional header matchers specific to this route.\nThese are evaluated in addition to the group-level headers.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HeaderMatcher"
                    }
                },
                "hostnames": {
                    "description": "Hostnames overrides the group-level hostname matchers for this specific route.\nAn empty slice inherits the group's hostnames.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "methods": {
                    "description": "Methods lists the HTTP methods this rule applies to.\nAn empty slice matches all methods.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "description": "Path is the exact path that must match.",
                    "type": "string"
                },
                "pathPrefix": {
                    "description": "PathPrefix is a prefix that the request path must start with.\nMutually exclusive with Path and PathRegex.",
                    "type": "string"
                },
                "pathRegex": {
                    "description": "PathRegex is a regular expression the request path must match.\nMutually exclusive with Path and PathPrefix.",
                    "type": "string"
                }
            }
        },
        "model.Route": {
            "type": "object",
            "properties": {
                "backends": {
                    "description": "Backends lists the upstream destinations for this route.\nWeights across all backends should sum to 100. If only one backend is\nprovided its weight is ignored and all traffic goes to it.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Backend"
                    }
                },
                "description": {
                    "description": "Description is an optional explanation of the route's purpose.",
                    "type": "string"
                },
                "groupId": {
                    "description": "GroupID is the identifier of the RouteGroup this route belongs to.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the route within its group.",
                    "type": "string"
                },
                "match": {
                    "description": "Match defines the conditions that a request must satisfy to be handled\nby this route. Path, method, hostname, and header matchers are supported.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.MatchRule"
                        }
                    ]
                },
                "name": {
                    "description": "Name is a human-readable label for the route.",
                    "type": "string"
                }
            }
        },
        "model.RouteGroup": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is an optional explanation of the group's purpose.",
                    "type": "string"
                },
                "headers": {
                    "description": "Headers are additional request header matchers applied to all routes in\nthis group. Routes can define their own headers on top of these.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HeaderMatcher"
                    }
                },
                "hostnames": {
                    "description": "Hostnames restricts this group to requests targeting specific virtual hosts.\nAn empty slice means the group matches all hostnames.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID is the unique identifier of the group.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a human-readable label for the group.",
                    "type": "string"
                },
                "prefix": {
                    "description": "Prefix is a path prefix applied to all routes in this group.\nExample: \"/api/v1\" will make a route with path \"/users\" match \"/api/v1/users\".",
                    "type": "string"
                },
                "routes": {
                    "description": "Routes holds all routes that belong to this group.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Route"
                    }
                }
            }
        },
        "respond.ErrorBody": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error contains a human-readable description of what went wrong.",
                    "type": "string",
                    "example": "group \"abc\" not found"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Rutoso API",
	Description:      "REST API control plane for Envoy proxies. Manage route groups and routes;\nchanges are pushed to all connected Envoy instances via xDS in real time.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
