// Vrata External Authorization Protocol v1
//
// This protocol defines the contract between Vrata and an external
// authorization service running in gRPC mode. The service receives a
// check request with the client's request metadata and returns an
// allow/deny decision.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: extauthz/v1/extauthz.proto

package extauthzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckRequest carries the client request metadata for authorization.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The HTTP method (GET, POST, etc.).
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// The request path.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Request headers as ordered key-value pairs.
	Headers []*HeaderPair `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	// The request body (only present when includeBody is enabled).
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_extauthz_v1_extauthz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CheckRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CheckRequest) GetHeaders() []*HeaderPair {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CheckRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// CheckResponse carries the authorization decision.
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the request is allowed.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// HTTP status code to return when denied. Ignored when allowed.
	DeniedStatus uint32 `protobuf:"varint,2,opt,name=denied_status,json=deniedStatus,proto3" json:"denied_status,omitempty"`
	// Headers to add to the upstream request (when allowed) or to the
	// client response (when denied).
	Headers []*HeaderPair `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	// Response body to return to the client when denied.
	DeniedBody    []byte `protobuf:"bytes,4,opt,name=denied_body,json=deniedBody,proto3" json:"denied_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_extauthz_v1_extauthz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetDeniedStatus() uint32 {
	if x != nil {
		return x.DeniedStatus
	}
	return 0
}

func (x *CheckResponse) GetHeaders() []*HeaderPair {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CheckResponse) GetDeniedBody() []byte {
	if x != nil {
		return x.DeniedBody
	}
	return nil
}

// HeaderPair is a single HTTP header key-value pair.
type HeaderPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderPair) Reset() {
	*x = HeaderPair{}
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPair) ProtoMessage() {}

func (x *HeaderPair) ProtoReflect() protoreflect.Message {
	mi := &file_extauthz_v1_extauthz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPair.ProtoReflect.Descriptor instead.
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return file_extauthz_v1_extauthz_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_extauthz_v1_extauthz_proto protoreflect.FileDescriptor

var file_extauthz_v1_extauthz_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x65, 0x78, 0x74, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78,
	0x74, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x78,
	0x74, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x0c, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x31, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x74, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xa2, 0x01,
	0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6e,
	0x69, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x78, 0x74, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x42, 0x6f,
	0x64, 0x79, 0x22, 0x34, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x4c, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x19, 0x2e, 0x65, 0x78, 0x74, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x65, 0x78, 0x74,
	0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x68, 0x65, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x63, 0x2f,
	0x76, 0x72, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x61,
	0x75, 0x74, 0x68, 0x7a, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x78, 0x74, 0x61, 0x75, 0x74, 0x68, 0x7a,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_extauthz_v1_extauthz_proto_rawDescOnce sync.Once
	file_extauthz_v1_extauthz_proto_rawDescData []byte
)

func file_extauthz_v1_extauthz_proto_rawDescGZIP() []byte {
	file_extauthz_v1_extauthz_proto_rawDescOnce.Do(func() {
		file_extauthz_v1_extauthz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extauthz_v1_extauthz_proto_rawDesc), len(file_extauthz_v1_extauthz_proto_rawDesc)))
	})
	return file_extauthz_v1_extauthz_proto_rawDescData
}

var file_extauthz_v1_extauthz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_extauthz_v1_extauthz_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: extauthz.v1.CheckRequest
	(*CheckResponse)(nil), // 1: extauthz.v1.CheckResponse
	(*HeaderPair)(nil),    // 2: extauthz.v1.HeaderPair
}
var file_extauthz_v1_extauthz_proto_depIdxs = []int32{
	2, // 0: extauthz.v1.CheckRequest.headers:type_name -> extauthz.v1.HeaderPair
	2, // 1: extauthz.v1.CheckResponse.headers:type_name -> extauthz.v1.HeaderPair
	0, // 2: extauthz.v1.Authorizer.Check:input_type -> extauthz.v1.CheckRequest
	1, // 3: extauthz.v1.Authorizer.Check:output_type -> extauthz.v1.CheckResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_extauthz_v1_extauthz_proto_init() }
func file_extauthz_v1_extauthz_proto_init() {
	if File_extauthz_v1_extauthz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extauthz_v1_extauthz_proto_rawDesc), len(file_extauthz_v1_extauthz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extauthz_v1_extauthz_proto_goTypes,
		DependencyIndexes: file_extauthz_v1_extauthz_proto_depIdxs,
		MessageInfos:      file_extauthz_v1_extauthz_proto_msgTypes,
	}.Build()
	File_extauthz_v1_extauthz_proto = out.File
	file_extauthz_v1_extauthz_proto_goTypes = nil
	file_extauthz_v1_extauthz_proto_depIdxs = nil
}
