// Copyright 2026 The Vrata Authors
// SPDX-License-Identifier: Apache-2.0

// Vrata External Processor Protocol v1
//
// This protocol defines the contract between Vrata and an external
// processor service. The processor receives HTTP request and response
// phases (headers, body) and can inspect, mutate, or reject them.
//
// Processors can be implemented in any language that supports gRPC or
// plain HTTP. See the Vrata documentation for implementation guides.
//
// Two transport modes are supported:
//   - gRPC: bidirectional stream via the Processor service below.
//   - HTTP: one POST request per phase to the processor endpoint,
//     with JSON-encoded ProcessingRequest/ProcessingResponse bodies.
//     Both modes have full feature parity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: extproc/v1/extproc.proto

package extprocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionStatus controls how Vrata proceeds after applying mutations.
type ActionStatus int32

const (
	// Apply mutations and continue normal processing through remaining phases.
	ActionStatus_CONTINUE ActionStatus = 0
	// Apply mutations and skip remaining phases for this direction.
	// When sent from a headers phase, replace_body in HeadersAction
	// replaces the original body entirely.
	ActionStatus_CONTINUE_AND_REPLACE ActionStatus = 1
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "CONTINUE",
		1: "CONTINUE_AND_REPLACE",
	}
	ActionStatus_value = map[string]int32{
		"CONTINUE":             0,
		"CONTINUE_AND_REPLACE": 1,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_extproc_v1_extproc_proto_enumTypes[0].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_extproc_v1_extproc_proto_enumTypes[0]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{0}
}

// ProcessingRequest is sent by Vrata to the processor for each
// configured phase of an HTTP transaction.
type ProcessingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Phase:
	//
	//	*ProcessingRequest_RequestHeaders
	//	*ProcessingRequest_ResponseHeaders
	//	*ProcessingRequest_RequestBody
	//	*ProcessingRequest_ResponseBody
	Phase isProcessingRequest_Phase `protobuf_oneof:"phase"`
	// When true, Vrata is in observe-only mode: the processor receives
	// data but must NOT respond. Any responses are silently ignored.
	ObserveOnly   bool `protobuf:"varint,5,opt,name=observe_only,json=observeOnly,proto3" json:"observe_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingRequest) Reset() {
	*x = ProcessingRequest{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingRequest) ProtoMessage() {}

func (x *ProcessingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingRequest.ProtoReflect.Descriptor instead.
func (*ProcessingRequest) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessingRequest) GetPhase() isProcessingRequest_Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *ProcessingRequest) GetRequestHeaders() *HttpHeaders {
	if x != nil {
		if x, ok := x.Phase.(*ProcessingRequest_RequestHeaders); ok {
			return x.RequestHeaders
		}
	}
	return nil
}

func (x *ProcessingRequest) GetResponseHeaders() *HttpHeaders {
	if x != nil {
		if x, ok := x.Phase.(*ProcessingRequest_ResponseHeaders); ok {
			return x.ResponseHeaders
		}
	}
	return nil
}

func (x *ProcessingRequest) GetRequestBody() *HttpBody {
	if x != nil {
		if x, ok := x.Phase.(*ProcessingRequest_RequestBody); ok {
			return x.RequestBody
		}
	}
	return nil
}

func (x *ProcessingRequest) GetResponseBody() *HttpBody {
	if x != nil {
		if x, ok := x.Phase.(*ProcessingRequest_ResponseBody); ok {
			return x.ResponseBody
		}
	}
	return nil
}

func (x *ProcessingRequest) GetObserveOnly() bool {
	if x != nil {
		return x.ObserveOnly
	}
	return false
}

type isProcessingRequest_Phase interface {
	isProcessingRequest_Phase()
}

type ProcessingRequest_RequestHeaders struct {
	// Request headers, sent before the request reaches the upstream.
	RequestHeaders *HttpHeaders `protobuf:"bytes,1,opt,name=request_headers,json=requestHeaders,proto3,oneof"`
}

type ProcessingRequest_ResponseHeaders struct {
	// Response headers, sent after the upstream replies.
	ResponseHeaders *HttpHeaders `protobuf:"bytes,2,opt,name=response_headers,json=responseHeaders,proto3,oneof"`
}

type ProcessingRequest_RequestBody struct {
	// A chunk of the request body (or the full body in buffered mode).
	RequestBody *HttpBody `protobuf:"bytes,3,opt,name=request_body,json=requestBody,proto3,oneof"`
}

type ProcessingRequest_ResponseBody struct {
	// A chunk of the response body (or the full body in buffered mode).
	ResponseBody *HttpBody `protobuf:"bytes,4,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*ProcessingRequest_RequestHeaders) isProcessingRequest_Phase() {}

func (*ProcessingRequest_ResponseHeaders) isProcessingRequest_Phase() {}

func (*ProcessingRequest_RequestBody) isProcessingRequest_Phase() {}

func (*ProcessingRequest_ResponseBody) isProcessingRequest_Phase() {}

// HttpHeaders carries the headers for a request or response phase.
type HttpHeaders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All headers as ordered key-value pairs. Duplicate keys are
	// preserved (e.g. multiple Set-Cookie headers).
	Headers []*HeaderPair `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// True when no body follows this headers message.
	EndOfStream   bool `protobuf:"varint,2,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeaders) Reset() {
	*x = HttpHeaders{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeaders) ProtoMessage() {}

func (x *HttpHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeaders.ProtoReflect.Descriptor instead.
func (*HttpHeaders) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{1}
}

func (x *HttpHeaders) GetHeaders() []*HeaderPair {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpHeaders) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

// HttpBody carries a chunk (or the entirety) of a request or response body.
type HttpBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The body bytes.
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// True when this is the last body chunk.
	EndOfStream   bool `protobuf:"varint,2,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpBody) Reset() {
	*x = HttpBody{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpBody) ProtoMessage() {}

func (x *HttpBody) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpBody.ProtoReflect.Descriptor instead.
func (*HttpBody) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{2}
}

func (x *HttpBody) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpBody) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

// HeaderPair is a single HTTP header key-value pair.
type HeaderPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderPair) Reset() {
	*x = HeaderPair{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPair) ProtoMessage() {}

func (x *HeaderPair) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPair.ProtoReflect.Descriptor instead.
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ProcessingResponse is sent by the processor back to Vrata after
// inspecting a phase. It tells Vrata what to do: continue (with
// optional mutations), replace the body, or reject the request.
type ProcessingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ProcessingResponse_RequestHeaders
	//	*ProcessingResponse_ResponseHeaders
	//	*ProcessingResponse_RequestBody
	//	*ProcessingResponse_ResponseBody
	//	*ProcessingResponse_Reject
	Action        isProcessingResponse_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingResponse) Reset() {
	*x = ProcessingResponse{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResponse) ProtoMessage() {}

func (x *ProcessingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingResponse.ProtoReflect.Descriptor instead.
func (*ProcessingResponse) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessingResponse) GetAction() isProcessingResponse_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ProcessingResponse) GetRequestHeaders() *HeadersAction {
	if x != nil {
		if x, ok := x.Action.(*ProcessingResponse_RequestHeaders); ok {
			return x.RequestHeaders
		}
	}
	return nil
}

func (x *ProcessingResponse) GetResponseHeaders() *HeadersAction {
	if x != nil {
		if x, ok := x.Action.(*ProcessingResponse_ResponseHeaders); ok {
			return x.ResponseHeaders
		}
	}
	return nil
}

func (x *ProcessingResponse) GetRequestBody() *BodyAction {
	if x != nil {
		if x, ok := x.Action.(*ProcessingResponse_RequestBody); ok {
			return x.RequestBody
		}
	}
	return nil
}

func (x *ProcessingResponse) GetResponseBody() *BodyAction {
	if x != nil {
		if x, ok := x.Action.(*ProcessingResponse_ResponseBody); ok {
			return x.ResponseBody
		}
	}
	return nil
}

func (x *ProcessingResponse) GetReject() *RejectRequest {
	if x != nil {
		if x, ok := x.Action.(*ProcessingResponse_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isProcessingResponse_Action interface {
	isProcessingResponse_Action()
}

type ProcessingResponse_RequestHeaders struct {
	// Respond to a request_headers phase.
	RequestHeaders *HeadersAction `protobuf:"bytes,1,opt,name=request_headers,json=requestHeaders,proto3,oneof"`
}

type ProcessingResponse_ResponseHeaders struct {
	// Respond to a response_headers phase.
	ResponseHeaders *HeadersAction `protobuf:"bytes,2,opt,name=response_headers,json=responseHeaders,proto3,oneof"`
}

type ProcessingResponse_RequestBody struct {
	// Respond to a request_body phase.
	RequestBody *BodyAction `protobuf:"bytes,3,opt,name=request_body,json=requestBody,proto3,oneof"`
}

type ProcessingResponse_ResponseBody struct {
	// Respond to a response_body phase.
	ResponseBody *BodyAction `protobuf:"bytes,4,opt,name=response_body,json=responseBody,proto3,oneof"`
}

type ProcessingResponse_Reject struct {
	// Reject the request immediately with a fixed response to the client.
	// Can be sent in response to any phase.
	Reject *RejectRequest `protobuf:"bytes,5,opt,name=reject,proto3,oneof"`
}

func (*ProcessingResponse_RequestHeaders) isProcessingResponse_Action() {}

func (*ProcessingResponse_ResponseHeaders) isProcessingResponse_Action() {}

func (*ProcessingResponse_RequestBody) isProcessingResponse_Action() {}

func (*ProcessingResponse_ResponseBody) isProcessingResponse_Action() {}

func (*ProcessingResponse_Reject) isProcessingResponse_Action() {}

// HeadersAction tells Vrata how to proceed after a headers phase.
type HeadersAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How to continue processing.
	Status ActionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=extproc.v1.ActionStatus" json:"status,omitempty"`
	// Headers to add or replace on the request/response.
	SetHeaders []*HeaderPair `protobuf:"bytes,2,rep,name=set_headers,json=setHeaders,proto3" json:"set_headers,omitempty"`
	// Header names to remove from the request/response.
	RemoveHeaders []string `protobuf:"bytes,3,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	// When status is CONTINUE_AND_REPLACE, this replaces the entire body.
	// Ignored when status is CONTINUE.
	ReplaceBody   []byte `protobuf:"bytes,4,opt,name=replace_body,json=replaceBody,proto3" json:"replace_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersAction) Reset() {
	*x = HeadersAction{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersAction) ProtoMessage() {}

func (x *HeadersAction) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersAction.ProtoReflect.Descriptor instead.
func (*HeadersAction) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{5}
}

func (x *HeadersAction) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_CONTINUE
}

func (x *HeadersAction) GetSetHeaders() []*HeaderPair {
	if x != nil {
		return x.SetHeaders
	}
	return nil
}

func (x *HeadersAction) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *HeadersAction) GetReplaceBody() []byte {
	if x != nil {
		return x.ReplaceBody
	}
	return nil
}

// BodyAction tells Vrata how to proceed after a body phase.
type BodyAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How to continue processing.
	Status ActionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=extproc.v1.ActionStatus" json:"status,omitempty"`
	// Headers to add or replace. Only effective in buffered body mode.
	SetHeaders []*HeaderPair `protobuf:"bytes,2,rep,name=set_headers,json=setHeaders,proto3" json:"set_headers,omitempty"`
	// Header names to remove. Only effective in buffered body mode.
	RemoveHeaders []string `protobuf:"bytes,3,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	// Body mutation — replace or clear the body.
	//
	// Types that are valid to be assigned to BodyMutation:
	//
	//	*BodyAction_ReplaceBody
	//	*BodyAction_ClearBody
	BodyMutation  isBodyAction_BodyMutation `protobuf_oneof:"body_mutation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyAction) Reset() {
	*x = BodyAction{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyAction) ProtoMessage() {}

func (x *BodyAction) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyAction.ProtoReflect.Descriptor instead.
func (*BodyAction) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{6}
}

func (x *BodyAction) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_CONTINUE
}

func (x *BodyAction) GetSetHeaders() []*HeaderPair {
	if x != nil {
		return x.SetHeaders
	}
	return nil
}

func (x *BodyAction) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *BodyAction) GetBodyMutation() isBodyAction_BodyMutation {
	if x != nil {
		return x.BodyMutation
	}
	return nil
}

func (x *BodyAction) GetReplaceBody() []byte {
	if x != nil {
		if x, ok := x.BodyMutation.(*BodyAction_ReplaceBody); ok {
			return x.ReplaceBody
		}
	}
	return nil
}

func (x *BodyAction) GetClearBody() bool {
	if x != nil {
		if x, ok := x.BodyMutation.(*BodyAction_ClearBody); ok {
			return x.ClearBody
		}
	}
	return false
}

type isBodyAction_BodyMutation interface {
	isBodyAction_BodyMutation()
}

type BodyAction_ReplaceBody struct {
	// Replace the body with these bytes.
	ReplaceBody []byte `protobuf:"bytes,4,opt,name=replace_body,json=replaceBody,proto3,oneof"`
}

type BodyAction_ClearBody struct {
	// Clear the body entirely when set to true.
	ClearBody bool `protobuf:"varint,5,opt,name=clear_body,json=clearBody,proto3,oneof"`
}

func (*BodyAction_ReplaceBody) isBodyAction_BodyMutation() {}

func (*BodyAction_ClearBody) isBodyAction_BodyMutation() {}

// RejectRequest tells Vrata to stop processing and return a fixed
// response to the client. The request never reaches the upstream.
type RejectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code to return (e.g. 403, 429).
	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Response headers to include.
	Headers []*HeaderPair `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	// Response body (if any).
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_extproc_v1_extproc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extproc_v1_extproc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_extproc_v1_extproc_proto_rawDescGZIP(), []int{7}
}

func (x *RejectRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RejectRequest) GetHeaders() []*HeaderPair {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RejectRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_extproc_v1_extproc_proto protoreflect.FileDescriptor

var file_extproc_v1_extproc_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x74,
	0x70, 0x72, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x78, 0x74, 0x70,
	0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x22, 0xc1, 0x02, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x48, 0x00,
	0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x44, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x74,
	0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65,
	0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x42, 0x6f,
	0x64, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72,
	0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x4f, 0x6e, 0x6c,
	0x79, 0x42, 0x07, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x0b, 0x48, 0x74,
	0x74, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74,
	0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x65,
	0x6e, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22,
	0x42, 0x0a, 0x08, 0x48, 0x74, 0x74, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x22, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x22, 0x34, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xdd, 0x02, 0x0a, 0x12, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x78, 0x74, 0x70,
	0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x46, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x3b,
	0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x3d, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x78, 0x74,
	0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42,
	0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc4, 0x01, 0x0a, 0x0d, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x65, 0x78,
	0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a,
	0x0b, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x73, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x22, 0xf5, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x64, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x37, 0x0a, 0x0b, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a,
	0x73, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x23, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6c,
	0x65, 0x61, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x0f, 0x0a, 0x0d, 0x62, 0x6f, 0x64, 0x79, 0x5f,
	0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x0d, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x30, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0x36, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4e, 0x54, 0x49,
	0x4e, 0x55, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55,
	0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x01, 0x32,
	0x59, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x07,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x68, 0x65, 0x74, 0x72, 0x6f,
	0x6e, 0x69, 0x63, 0x2f, 0x76, 0x72, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x78, 0x74, 0x70, 0x72,
	0x6f, 0x63, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_extproc_v1_extproc_proto_rawDescOnce sync.Once
	file_extproc_v1_extproc_proto_rawDescData []byte
)

func file_extproc_v1_extproc_proto_rawDescGZIP() []byte {
	file_extproc_v1_extproc_proto_rawDescOnce.Do(func() {
		file_extproc_v1_extproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extproc_v1_extproc_proto_rawDesc), len(file_extproc_v1_extproc_proto_rawDesc)))
	})
	return file_extproc_v1_extproc_proto_rawDescData
}

var file_extproc_v1_extproc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extproc_v1_extproc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_extproc_v1_extproc_proto_goTypes = []any{
	(ActionStatus)(0),          // 0: extproc.v1.ActionStatus
	(*ProcessingRequest)(nil),  // 1: extproc.v1.ProcessingRequest
	(*HttpHeaders)(nil),        // 2: extproc.v1.HttpHeaders
	(*HttpBody)(nil),           // 3: extproc.v1.HttpBody
	(*HeaderPair)(nil),         // 4: extproc.v1.HeaderPair
	(*ProcessingResponse)(nil), // 5: extproc.v1.ProcessingResponse
	(*HeadersAction)(nil),      // 6: extproc.v1.HeadersAction
	(*BodyAction)(nil),         // 7: extproc.v1.BodyAction
	(*RejectRequest)(nil),      // 8: extproc.v1.RejectRequest
}
var file_extproc_v1_extproc_proto_depIdxs = []int32{
	2,  // 0: extproc.v1.ProcessingRequest.request_headers:type_name -> extproc.v1.HttpHeaders
	2,  // 1: extproc.v1.ProcessingRequest.response_headers:type_name -> extproc.v1.HttpHeaders
	3,  // 2: extproc.v1.ProcessingRequest.request_body:type_name -> extproc.v1.HttpBody
	3,  // 3: extproc.v1.ProcessingRequest.response_body:type_name -> extproc.v1.HttpBody
	4,  // 4: extproc.v1.HttpHeaders.headers:type_name -> extproc.v1.HeaderPair
	6,  // 5: extproc.v1.ProcessingResponse.request_headers:type_name -> extproc.v1.HeadersAction
	6,  // 6: extproc.v1.ProcessingResponse.response_headers:type_name -> extproc.v1.HeadersAction
	7,  // 7: extproc.v1.ProcessingResponse.request_body:type_name -> extproc.v1.BodyAction
	7,  // 8: extproc.v1.ProcessingResponse.response_body:type_name -> extproc.v1.BodyAction
	8,  // 9: extproc.v1.ProcessingResponse.reject:type_name -> extproc.v1.RejectRequest
	0,  // 10: extproc.v1.HeadersAction.status:type_name -> extproc.v1.ActionStatus
	4,  // 11: extproc.v1.HeadersAction.set_headers:type_name -> extproc.v1.HeaderPair
	0,  // 12: extproc.v1.BodyAction.status:type_name -> extproc.v1.ActionStatus
	4,  // 13: extproc.v1.BodyAction.set_headers:type_name -> extproc.v1.HeaderPair
	4,  // 14: extproc.v1.RejectRequest.headers:type_name -> extproc.v1.HeaderPair
	1,  // 15: extproc.v1.Processor.Process:input_type -> extproc.v1.ProcessingRequest
	5,  // 16: extproc.v1.Processor.Process:output_type -> extproc.v1.ProcessingResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_extproc_v1_extproc_proto_init() }
func file_extproc_v1_extproc_proto_init() {
	if File_extproc_v1_extproc_proto != nil {
		return
	}
	file_extproc_v1_extproc_proto_msgTypes[0].OneofWrappers = []any{
		(*ProcessingRequest_RequestHeaders)(nil),
		(*ProcessingRequest_ResponseHeaders)(nil),
		(*ProcessingRequest_RequestBody)(nil),
		(*ProcessingRequest_ResponseBody)(nil),
	}
	file_extproc_v1_extproc_proto_msgTypes[4].OneofWrappers = []any{
		(*ProcessingResponse_RequestHeaders)(nil),
		(*ProcessingResponse_ResponseHeaders)(nil),
		(*ProcessingResponse_RequestBody)(nil),
		(*ProcessingResponse_ResponseBody)(nil),
		(*ProcessingResponse_Reject)(nil),
	}
	file_extproc_v1_extproc_proto_msgTypes[6].OneofWrappers = []any{
		(*BodyAction_ReplaceBody)(nil),
		(*BodyAction_ClearBody)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extproc_v1_extproc_proto_rawDesc), len(file_extproc_v1_extproc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extproc_v1_extproc_proto_goTypes,
		DependencyIndexes: file_extproc_v1_extproc_proto_depIdxs,
		EnumInfos:         file_extproc_v1_extproc_proto_enumTypes,
		MessageInfos:      file_extproc_v1_extproc_proto_msgTypes,
	}.Build()
	File_extproc_v1_extproc_proto = out.File
	file_extproc_v1_extproc_proto_goTypes = nil
	file_extproc_v1_extproc_proto_depIdxs = nil
}
