// Package api wires together all HTTP routes and middleware for the Rutoso REST API.
package api

import (
	"log/slog"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	swagV2 "github.com/swaggo/swag/v2"

	_ "github.com/achetronic/rutoso/docs" // generated by swag init
	"github.com/achetronic/rutoso/internal/api/handlers"
	"github.com/achetronic/rutoso/internal/api/middleware"
	"github.com/achetronic/rutoso/internal/store"
)

// NewRouter creates and returns the root http.Handler for the Rutoso REST API.
// raftApplier is optional; pass nil when running in single-node mode.
func NewRouter(st store.Store, logger *slog.Logger, raftApplier handlers.RaftApplier) http.Handler {
	mux := http.NewServeMux()

	deps := &handlers.Dependencies{
		Store:  st,
		Logger: logger,
		Raft:   raftApplier,
	}

	// Route endpoints
	mux.HandleFunc("GET /api/v1/routes", deps.ListRoutes)
	mux.HandleFunc("POST /api/v1/routes", deps.CreateRoute)
	mux.HandleFunc("GET /api/v1/routes/{routeId}", deps.GetRoute)
	mux.HandleFunc("PUT /api/v1/routes/{routeId}", deps.UpdateRoute)
	mux.HandleFunc("DELETE /api/v1/routes/{routeId}", deps.DeleteRoute)

	// Group endpoints
	mux.HandleFunc("GET /api/v1/groups", deps.ListGroups)
	mux.HandleFunc("POST /api/v1/groups", deps.CreateGroup)
	mux.HandleFunc("GET /api/v1/groups/{groupId}", deps.GetGroup)
	mux.HandleFunc("PUT /api/v1/groups/{groupId}", deps.UpdateGroup)
	mux.HandleFunc("DELETE /api/v1/groups/{groupId}", deps.DeleteGroup)

	// Middleware endpoints
	mux.HandleFunc("GET /api/v1/middlewares", deps.ListMiddlewares)
	mux.HandleFunc("POST /api/v1/middlewares", deps.CreateMiddleware)
	mux.HandleFunc("GET /api/v1/middlewares/{middlewareId}", deps.GetMiddleware)
	mux.HandleFunc("PUT /api/v1/middlewares/{middlewareId}", deps.UpdateMiddleware)
	mux.HandleFunc("DELETE /api/v1/middlewares/{middlewareId}", deps.DeleteMiddleware)

	// Listener endpoints
	mux.HandleFunc("GET /api/v1/listeners", deps.ListListeners)
	mux.HandleFunc("POST /api/v1/listeners", deps.CreateListener)
	mux.HandleFunc("GET /api/v1/listeners/{listenerId}", deps.GetListener)
	mux.HandleFunc("PUT /api/v1/listeners/{listenerId}", deps.UpdateListener)
	mux.HandleFunc("DELETE /api/v1/listeners/{listenerId}", deps.DeleteListener)

	// Destination endpoints
	mux.HandleFunc("GET /api/v1/destinations", deps.ListDestinations)

	// Sync (SSE stream for proxy-mode instances)
	mux.HandleFunc("GET /api/v1/sync/stream", deps.SyncStream)

	// Snapshot endpoints
	mux.HandleFunc("GET /api/v1/snapshots", deps.ListSnapshots)
	mux.HandleFunc("POST /api/v1/snapshots", deps.CreateSnapshot)
	mux.HandleFunc("GET /api/v1/snapshots/{snapshotId}", deps.GetSnapshot)
	mux.HandleFunc("DELETE /api/v1/snapshots/{snapshotId}", deps.DeleteSnapshot)
	mux.HandleFunc("POST /api/v1/snapshots/{snapshotId}/activate", deps.ActivateSnapshot)

	// Internal Raft endpoint (cluster mode only)
	mux.HandleFunc("POST /api/v1/internal/raft/apply", deps.RaftApply)

	// Debug
	mux.HandleFunc("GET /api/v1/debug/config", deps.GetConfigDump)
	mux.HandleFunc("POST /api/v1/destinations", deps.CreateDestination)
	mux.HandleFunc("GET /api/v1/destinations/{destinationId}", deps.GetDestination)
	mux.HandleFunc("PUT /api/v1/destinations/{destinationId}", deps.UpdateDestination)
	mux.HandleFunc("DELETE /api/v1/destinations/{destinationId}", deps.DeleteDestination)

	// Swagger UI
	mux.HandleFunc("GET /api/v1/docs/doc.json", func(w http.ResponseWriter, r *http.Request) {
		doc, err := swagV2.ReadDoc("swagger")
		if err != nil {
			http.Error(w, "failed to read OpenAPI spec: "+err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, _ = w.Write([]byte(doc))
	})

	mux.Handle("/api/v1/docs/", httpSwagger.Handler(
		httpSwagger.URL("/api/v1/docs/doc.json"),
	))

	// Chain middleware: recovery wraps logger wraps mux.
	return middleware.Recovery(logger)(middleware.Logger(logger)(mux))
}
