// Copyright 2026 The Vrata Authors
// SPDX-License-Identifier: Apache-2.0

// Package api wires together all HTTP routes and middleware for the Vrata REST API.
package api

import (
	"log/slog"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	swagV2 "github.com/swaggo/swag/v2"

	_ "github.com/achetronic/vrata/docs" // generated by swag init
	"github.com/achetronic/vrata/internal/api/handlers"
	"github.com/achetronic/vrata/internal/api/middleware"
	"github.com/achetronic/vrata/internal/api/respond"
	"github.com/achetronic/vrata/internal/config"
	"github.com/achetronic/vrata/internal/store"
)

// NewRouter creates and returns the root http.Handler for the Vrata REST API.
// raftApplier is optional; pass nil when running in single-node mode.
// apiKeys is optional; when nil or empty, no authentication is required.
func NewRouter(st store.Store, logger *slog.Logger, raftApplier handlers.RaftApplier, apiKeys []config.APIKeyEntry) http.Handler {
	mux := http.NewServeMux()

	deps := &handlers.Dependencies{
		Store:  st,
		Logger: logger,
		Raft:   raftApplier,
	}

	// Route endpoints
	mux.HandleFunc("GET /api/v1/routes", deps.ListRoutes)
	mux.HandleFunc("POST /api/v1/routes", deps.CreateRoute)
	mux.HandleFunc("GET /api/v1/routes/{routeId}", deps.GetRoute)
	mux.HandleFunc("PUT /api/v1/routes/{routeId}", deps.UpdateRoute)
	mux.HandleFunc("DELETE /api/v1/routes/{routeId}", deps.DeleteRoute)

	// Group endpoints
	mux.HandleFunc("GET /api/v1/groups", deps.ListGroups)
	mux.HandleFunc("POST /api/v1/groups", deps.CreateGroup)
	mux.HandleFunc("GET /api/v1/groups/{groupId}", deps.GetGroup)
	mux.HandleFunc("PUT /api/v1/groups/{groupId}", deps.UpdateGroup)
	mux.HandleFunc("DELETE /api/v1/groups/{groupId}", deps.DeleteGroup)

	// Middleware endpoints
	mux.HandleFunc("GET /api/v1/middlewares", deps.ListMiddlewares)
	mux.HandleFunc("POST /api/v1/middlewares", deps.CreateMiddleware)
	mux.HandleFunc("GET /api/v1/middlewares/{middlewareId}", deps.GetMiddleware)
	mux.HandleFunc("PUT /api/v1/middlewares/{middlewareId}", deps.UpdateMiddleware)
	mux.HandleFunc("DELETE /api/v1/middlewares/{middlewareId}", deps.DeleteMiddleware)

	// Listener endpoints
	mux.HandleFunc("GET /api/v1/listeners", deps.ListListeners)
	mux.HandleFunc("POST /api/v1/listeners", deps.CreateListener)
	mux.HandleFunc("GET /api/v1/listeners/{listenerId}", deps.GetListener)
	mux.HandleFunc("PUT /api/v1/listeners/{listenerId}", deps.UpdateListener)
	mux.HandleFunc("DELETE /api/v1/listeners/{listenerId}", deps.DeleteListener)

	// Destination endpoints
	mux.HandleFunc("GET /api/v1/destinations", deps.ListDestinations)

	// Secret endpoints
	mux.HandleFunc("GET /api/v1/secrets", deps.ListSecrets)
	mux.HandleFunc("POST /api/v1/secrets", deps.CreateSecret)
	mux.HandleFunc("GET /api/v1/secrets/{secretId}", deps.GetSecret)
	mux.HandleFunc("PUT /api/v1/secrets/{secretId}", deps.UpdateSecret)
	mux.HandleFunc("DELETE /api/v1/secrets/{secretId}", deps.DeleteSecret)

	// Sync — snapshot streaming to proxies and Raft write-forwarding between nodes
	mux.HandleFunc("GET /api/v1/sync/snapshot", deps.SyncSnapshot)
	mux.HandleFunc("POST /api/v1/sync/raft", deps.RaftApply)

	// Snapshot endpoints
	mux.HandleFunc("GET /api/v1/snapshots", deps.ListSnapshots)
	mux.HandleFunc("POST /api/v1/snapshots", deps.CreateSnapshot)
	mux.HandleFunc("GET /api/v1/snapshots/{snapshotId}", deps.GetSnapshot)
	mux.HandleFunc("DELETE /api/v1/snapshots/{snapshotId}", deps.DeleteSnapshot)
	mux.HandleFunc("POST /api/v1/snapshots/{snapshotId}/activate", deps.ActivateSnapshot)

	// Debug
	mux.HandleFunc("GET /api/v1/debug/config", deps.GetConfigDump)
	mux.HandleFunc("POST /api/v1/destinations", deps.CreateDestination)
	mux.HandleFunc("GET /api/v1/destinations/{destinationId}", deps.GetDestination)
	mux.HandleFunc("PUT /api/v1/destinations/{destinationId}", deps.UpdateDestination)
	mux.HandleFunc("DELETE /api/v1/destinations/{destinationId}", deps.DeleteDestination)

	// Swagger UI
	mux.HandleFunc("GET /api/v1/docs/doc.json", func(w http.ResponseWriter, r *http.Request) {
		doc, err := swagV2.ReadDoc("swagger")
		if err != nil {
			respond.Error(w, http.StatusInternalServerError, "failed to read OpenAPI spec", logger)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, _ = w.Write([]byte(doc))
	})

	mux.Handle("/api/v1/docs/", httpSwagger.Handler(
		httpSwagger.URL("/api/v1/docs/doc.json"),
	))

	// Chain middleware: recovery wraps auth wraps logger wraps mux.
	return middleware.Recovery(logger)(middleware.Auth(apiKeys, logger)(middleware.Logger(logger)(mux)))
}
