// Copyright 2026 The Vrata Authors
// SPDX-License-Identifier: Apache-2.0

// Package api wires together all HTTP routes and middleware for the Vrata REST API.
package api

import (
	"log/slog"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	swagV2 "github.com/swaggo/swag/v2"

	_ "github.com/achetronic/vrata/docs" // generated by swag init
	"github.com/achetronic/vrata/internal/api/handlers"
	"github.com/achetronic/vrata/internal/api/middleware"
	"github.com/achetronic/vrata/internal/api/respond"
	"github.com/achetronic/vrata/internal/config"
	"github.com/achetronic/vrata/internal/store"
)

// NewRouter creates and returns the root http.Handler for the Vrata REST API.
// raftApplier is optional; pass nil when running in single-node mode.
// apiKeys is optional; when nil or empty, no authentication is required.
func NewRouter(st store.Store, logger *slog.Logger, raftApplier handlers.RaftApplier, apiKeys []config.APIKeyEntry) http.Handler {
	mux := http.NewServeMux()

	deps := &handlers.Dependencies{
		Store:  st,
		Logger: logger,
		Raft:   raftApplier,
	}

	// Route endpoints
	mux.HandleFunc("GET /api/v1/routes", deps.HandleListRoutes)
	mux.HandleFunc("POST /api/v1/routes", deps.HandleCreateRoute)
	mux.HandleFunc("GET /api/v1/routes/{routeId}", deps.HandleGetRoute)
	mux.HandleFunc("PUT /api/v1/routes/{routeId}", deps.HandleUpdateRoute)
	mux.HandleFunc("DELETE /api/v1/routes/{routeId}", deps.HandleDeleteRoute)

	// Group endpoints
	mux.HandleFunc("GET /api/v1/groups", deps.HandleListGroups)
	mux.HandleFunc("POST /api/v1/groups", deps.HandleCreateGroup)
	mux.HandleFunc("GET /api/v1/groups/{groupId}", deps.HandleGetGroup)
	mux.HandleFunc("PUT /api/v1/groups/{groupId}", deps.HandleUpdateGroup)
	mux.HandleFunc("DELETE /api/v1/groups/{groupId}", deps.HandleDeleteGroup)

	// Middleware endpoints
	mux.HandleFunc("GET /api/v1/middlewares", deps.HandleListMiddlewares)
	mux.HandleFunc("POST /api/v1/middlewares", deps.HandleCreateMiddleware)
	mux.HandleFunc("GET /api/v1/middlewares/{middlewareId}", deps.HandleGetMiddleware)
	mux.HandleFunc("PUT /api/v1/middlewares/{middlewareId}", deps.HandleUpdateMiddleware)
	mux.HandleFunc("DELETE /api/v1/middlewares/{middlewareId}", deps.HandleDeleteMiddleware)

	// Listener endpoints
	mux.HandleFunc("GET /api/v1/listeners", deps.HandleListListeners)
	mux.HandleFunc("POST /api/v1/listeners", deps.HandleCreateListener)
	mux.HandleFunc("GET /api/v1/listeners/{listenerId}", deps.HandleGetListener)
	mux.HandleFunc("PUT /api/v1/listeners/{listenerId}", deps.HandleUpdateListener)
	mux.HandleFunc("DELETE /api/v1/listeners/{listenerId}", deps.HandleDeleteListener)

	// Destination endpoints
	mux.HandleFunc("GET /api/v1/destinations", deps.HandleListDestinations)
	mux.HandleFunc("POST /api/v1/destinations", deps.HandleCreateDestination)
	mux.HandleFunc("GET /api/v1/destinations/{destinationId}", deps.HandleGetDestination)
	mux.HandleFunc("PUT /api/v1/destinations/{destinationId}", deps.HandleUpdateDestination)
	mux.HandleFunc("DELETE /api/v1/destinations/{destinationId}", deps.HandleDeleteDestination)

	// Secret endpoints
	mux.HandleFunc("GET /api/v1/secrets", deps.HandleListSecrets)
	mux.HandleFunc("POST /api/v1/secrets", deps.HandleCreateSecret)
	mux.HandleFunc("GET /api/v1/secrets/{secretId}", deps.HandleGetSecret)
	mux.HandleFunc("PUT /api/v1/secrets/{secretId}", deps.HandleUpdateSecret)
	mux.HandleFunc("DELETE /api/v1/secrets/{secretId}", deps.HandleDeleteSecret)

	// Sync — snapshot streaming to proxies and Raft write-forwarding between nodes
	mux.HandleFunc("GET /api/v1/sync/snapshot", deps.HandleSyncSnapshot)
	mux.HandleFunc("POST /api/v1/sync/raft", deps.HandleRaftApply)

	// Snapshot endpoints
	mux.HandleFunc("GET /api/v1/snapshots", deps.HandleListSnapshots)
	mux.HandleFunc("POST /api/v1/snapshots", deps.HandleCreateSnapshot)
	mux.HandleFunc("GET /api/v1/snapshots/{snapshotId}", deps.HandleGetSnapshot)
	mux.HandleFunc("DELETE /api/v1/snapshots/{snapshotId}", deps.HandleDeleteSnapshot)
	mux.HandleFunc("POST /api/v1/snapshots/{snapshotId}/activate", deps.HandleActivateSnapshot)

	// Debug
	mux.HandleFunc("GET /api/v1/debug/config", deps.HandleGetConfigDump)

	// Swagger UI
	mux.HandleFunc("GET /api/v1/docs/doc.json", func(w http.ResponseWriter, r *http.Request) {
		doc, err := swagV2.ReadDoc("swagger")
		if err != nil {
			respond.Error(w, http.StatusInternalServerError, "failed to read OpenAPI spec", logger)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		// Swagger doc response — write error is not actionable.
		_, _ = w.Write([]byte(doc))
	})

	mux.Handle("/api/v1/docs/", httpSwagger.Handler(
		httpSwagger.URL("/api/v1/docs/doc.json"),
	))

	// Chain middleware: recovery wraps auth wraps logger wraps mux.
	return middleware.Recovery(logger)(middleware.Auth(apiKeys, logger)(middleware.Logger(logger)(mux)))
}
